#!/usr/bin/python

import digitalocean
import sys

TOKEN='<YOUR-TOKEN-HERE>'

droplet = digitalocean.Droplet(token=TOKEN,
                               name=sys.argv[1],
                               region='fra1',
                               image='centos-7-2-x64',
                               size_slug='512mb',
                               backups=False)

droplet.create()
